name: deroli_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dotted_border: "^2.0.0"
  google_fonts: ^6.2.1
  go_router: ^14.0.0
  http: ^1.6.0
  currency_text_input_formatter: ^2.3.0
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  gap: ^3.0.1
  provider: ^6.1.5+1
  drops: ^0.0.5
  icons_plus: ^5.0.0
  file_picker: ^8.0.0
  permission_handler: ^12.0.1
  liquid_glass_renderer: ^0.2.0-dev.4
  motor: ^1.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf

    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-SemiBold.ttf

    - family: FredokaBold
      fonts:
        - asset: assets/fonts/Fredoka-Medium.ttf

    - family: FredokaMedium
      fonts:
        - asset: assets/fonts/Fredoka-SemiBold.ttf

    - family: Trap
      fonts:
        - asset: fonts/trap/Trap-Black.otf
        - asset: fonts/trap/Trap-Bold.otf
        - asset: fonts/trap/Trap-ExtraBold.otf
        - asset: fonts/trap/Trap-Light.otf
        - asset: fonts/trap/Trap-Medium.otf
        - asset: fonts/trap/Trap-Regular.otf
        - asset: fonts/trap/Trap-SemiBold.otf
